// 每日成语 · 内置成语库
// 每项：idiom(成语) pinyin(成语拼音) chars(四字逐字+拼音)
//       meaningCn(中文释义) meaningEn(英文释义)
//       exampleCn(例句) examplePy(例句拼音) exampleEn(例句英译)
//       tone(R=红卡 G=绿卡) —— 用于配色风格，参考文献的红色/绿色卡片
var IDIOMS = [
  {
    idiom: "如鱼得水",
    pinyin: "rú yú dé shuǐ",
    chars: [
      { c: "如", p: "rú" },
      { c: "鱼", p: "yú" },
      { c: "得", p: "dé" },
      { c: "水", p: "shuǐ" },
    ],
    meaningCn: "像鱼得到水一样。比喻得到跟自己十分投合的人，或进入对自己很合适的环境。",
    meaningEn: "Completely in one’s element; a perfect fit of person and place.",
    exampleCn: "他到了新公司，工作起来如鱼得水。",
    examplePy: "Tā dào le xīn gōngsī, gōngzuò qǐlái rú yú dé shuǐ.",
    exampleEn: "The new company job fits him so well that it's completely in his element.",
    tone: "R",
  },
  {
    idiom: "否极泰来",
    pinyin: "pǐ jí tài lái",
    chars: [
      { c: "否", p: "pǐ" },
      { c: "极", p: "jí" },
      { c: "泰", p: "tài" },
      { c: "来", p: "lái" },
    ],
    meaningCn: "坏运气到了尽头，好运气就会到来。",
    meaningEn: "When things are at their worst, they turn for the better.",
    exampleCn: "熬过这段日子，就会否极泰来。",
    examplePy: "Áo guò zhè duàn rìzi, jiù huì pǐ jí tài lái.",
    exampleEn: "Get through this rough patch and things will start looking up.",
    tone: "G",
  },
  {
    idiom: "画蛇添足",
    pinyin: "huà shé tiān zú",
    chars: [
      { c: "画", p: "huà" },
      { c: "蛇", p: "shé" },
      { c: "添", p: "tiān" },
      { c: "足", p: "zú" },
    ],
    meaningCn: "画蛇时给蛇添上脚。比喻做了多余的事，反而不恰当。",
    meaningEn: "To add feet when drawing a snake — to overdo something and spoil it.",
    exampleCn: "文章结尾再加一段，反而画蛇添足了。",
    examplePy: "Wénzhāng jiéwěi zài jiā yí duàn, fǎn'ér huà shé tiān zú le.",
    exampleEn: "Adding another paragraph at the end only spoils the essay.",
    tone: "R",
  },
  {
    idiom: "亡羊补牢",
    pinyin: "wáng yáng bǔ láo",
    chars: [
      { c: "亡", p: "wáng" },
      { c: "羊", p: "yáng" },
      { c: "补", p: "bǔ" },
      { c: "牢", p: "láo" },
    ],
    meaningCn: "羊丢了才修补羊圈。比喻出了问题以后想办法补救，可以防止继续受损失。",
    meaningEn: "To mend the fold after a sheep is lost — to fix the problem before it gets worse.",
    exampleCn: "现在改进还来得及，亡羊补牢，为时未晚。",
    examplePy: "Xiànzài gǎijìn hái láidejí, wáng yáng bǔ láo, wéi shí wèi wǎn.",
    exampleEn: "It's not too late to mend the fold after losing a sheep.",
    tone: "G",
  },
  {
    idiom: "守株待兔",
    pinyin: "shǒu zhū dài tù",
    chars: [
      { c: "守", p: "shǒu" },
      { c: "株", p: "zhū" },
      { c: "待", p: "dài" },
      { c: "兔", p: "tù" },
    ],
    meaningCn: "比喻不主动努力，而存侥幸心理，希望得到意外的收获。",
    meaningEn: "To wait by a tree stump for a rabbit — to rely on luck instead of effort.",
    exampleCn: "与其守株待兔，不如主动出击。",
    examplePy: "Yǔqí shǒu zhū dài tù, bùrú zhǔdòng chūjī.",
    exampleEn: "Rather than wait for luck, you should take the initiative.",
    tone: "R",
  },
  {
    idiom: "掩耳盗铃",
    pinyin: "yǎn ěr dào líng",
    chars: [
      { c: "掩", p: "yǎn" },
      { c: "耳", p: "ěr" },
      { c: "盗", p: "dào" },
      { c: "铃", p: "líng" },
    ],
    meaningCn: "捂住耳朵偷铃铛。比喻自己欺骗自己。",
    meaningEn: "To cover one's ears while stealing a bell — to deceive oneself.",
    exampleCn: "他不愿面对现实，简直是掩耳盗铃。",
    examplePy: "Tā bú yuàn miànduì xiànshí, jiǎnzhí shì yǎn ěr dào líng.",
    exampleEn: "Refusing to face reality is like covering your ears to steal a bell.",
    tone: "G",
  },
  {
    idiom: "刻舟求剑",
    pinyin: "kè zhōu qiú jiàn",
    chars: [
      { c: "刻", p: "kè" },
      { c: "舟", p: "zhōu" },
      { c: "求", p: "qiú" },
      { c: "剑", p: "jiàn" },
    ],
    meaningCn: "在船上刻记号找掉落的剑。比喻拘泥成法，固执不知变通。",
    meaningEn: "To carve a mark on the boat to find a dropped sword — to be rigid and inflexible.",
    exampleCn: "时代变了，不能刻舟求剑地照搬旧方法。",
    examplePy: "Shídài biàn le, bùnéng kè zhōu qiú jiàn de zhàobān jiù fāngfǎ.",
    exampleEn: "Times have changed; don't insist on the old rigid methods.",
    tone: "R",
  },
  {
    idiom: "狐假虎威",
    pinyin: "hú jiǎ hǔ wēi",
    chars: [
      { c: "狐", p: "hú" },
      { c: "假", p: "jiǎ" },
      { c: "虎", p: "hǔ" },
      { c: "威", p: "wēi" },
    ],
    meaningCn: "狐狸假借老虎的威势。比喻依仗别人的势力欺压人。",
    meaningEn: "The fox borrows the tiger's might — to bully others using someone else's power.",
    exampleCn: "他仗着上司撑腰，狐假虎威，四处欺压同事。",
    examplePy: "Tā zhàngzhe shàngsi chēngyāo, hú jiǎ hǔ wēi, sìchù qīyā tóngshì.",
    exampleEn: "Relying on his boss's backing, he plays the fox borrowing the tiger's might.",
    tone: "G",
  },
  {
    idiom: "井底之蛙",
    pinyin: "jǐng dǐ zhī wā",
    chars: [
      { c: "井", p: "jǐng" },
      { c: "底", p: "dǐ" },
      { c: "之", p: "zhī" },
      { c: "蛙", p: "wā" },
    ],
    meaningCn: "井底的青蛙。比喻见识短浅的人。",
    meaningEn: "A frog at the bottom of a well — a person of limited outlook.",
    exampleCn: "他足不出户，如同井底之蛙。",
    examplePy: "Tā zú bù chū hù, rútóng jǐng dǐ zhī wā.",
    exampleEn: "Never leaving home, he's like a frog in a well.",
    tone: "R",
  },
  {
    idiom: "对牛弹琴",
    pinyin: "duì niú tán qín",
    chars: [
      { c: "对", p: "duì" },
      { c: "牛", p: "niú" },
      { c: "弹", p: "tán" },
      { c: "琴", p: "qín" },
    ],
    meaningCn: "比喻对不懂道理的人讲道理，或对外行人说内行话。",
    meaningEn: "To play the lute to a cow — to reason with someone who doesn't understand.",
    exampleCn: "跟他解释半天，无异于对牛弹琴。",
    examplePy: "Gēn tā jiěshì bàntiān, wúyì yú duì niú tán qín.",
    exampleEn: "Explaining to him for ages is like playing music to a cow.",
    tone: "G",
  },
  {
    idiom: "杯弓蛇影",
    pinyin: "bēi gōng shé yǐng",
    chars: [
      { c: "杯", p: "bēi" },
      { c: "弓", p: "gōng" },
      { c: "蛇", p: "shé" },
      { c: "影", p: "yǐng" },
    ],
    meaningCn: "把杯中的弓影当成蛇。比喻因疑神疑鬼而自惊自怕。",
    meaningEn: "To mistake a reflection of a bow in the cup for a snake — to be overly suspicious.",
    exampleCn: "别总是杯弓蛇影，自己吓自己。",
    examplePy: "Bié zǒngshì bēi gōng shé yǐng, zìjǐ xià zìjǐ.",
    exampleEn: "Don't be so jumpy and scare yourself over nothing.",
    tone: "R",
  },
  {
    idiom: "滥竽充数",
    pinyin: "làn yú chōng shù",
    chars: [
      { c: "滥", p: "làn" },
      { c: "竽", p: "yú" },
      { c: "充", p: "chōng" },
      { c: "数", p: "shù" },
    ],
    meaningCn: "不会吹竽的人混在乐队里充数。比喻没有真才实学的人混在行家里凑数。",
    meaningEn: "To fill up the ranks with the unqualified — to be a pretender among experts.",
    exampleCn: "他根本不懂技术，只是滥竽充数。",
    examplePy: "Tā gēnběn bù dǒng jìshù, zhǐshì làn yú chōng shù.",
    exampleEn: "He knows nothing about the craft; he's just filling the ranks.",
    tone: "G",
  },
  {
    idiom: "叶公好龙",
    pinyin: "yè gōng hào lóng",
    chars: [
      { c: "叶", p: "yè" },
      { c: "公", p: "gōng" },
      { c: "好", p: "hào" },
      { c: "龙", p: "lóng" },
    ],
    meaningCn: "比喻口头上说爱好某事物，实际上并不真爱好。",
    meaningEn: "Lord Ye's love of dragons — to profess a love one doesn't truly have.",
    exampleCn: "他嘴上说热爱艺术，实则叶公好龙。",
    examplePy: "Tā zuǐshang shuō rè'ài yìshù, shízé yè gōng hào lóng.",
    exampleEn: "He talks about loving art but doesn't really mean it.",
    tone: "R",
  },
  {
    idiom: "自相矛盾",
    pinyin: "zì xiāng máo dùn",
    chars: [
      { c: "自", p: "zì" },
      { c: "相", p: "xiāng" },
      { c: "矛", p: "máo" },
      { c: "盾", p: "dùn" },
    ],
    meaningCn: "比喻自己说话做事前后抵触，互相冲突。",
    meaningEn: "To contradict oneself — self-defeating logic.",
    exampleCn: "他这番话前后不一致，自相矛盾。",
    examplePy: "Tā zhè fān huà qiánhòu bù yízhì, zì xiāng máo dùn.",
    exampleEn: "His remarks contradict each other.",
    tone: "G",
  },
  {
    idiom: "揠苗助长",
    pinyin: "yà miáo zhù zhǎng",
    chars: [
      { c: "揠", p: "yà" },
      { c: "苗", p: "miáo" },
      { c: "助", p: "zhù" },
      { c: "长", p: "zhǎng" },
    ],
    meaningCn: "把禾苗拔高帮助它生长。比喻违反事物发展规律，急于求成，反而坏事。",
    meaningEn: "To pull up seedlings to help them grow — to spoil things by being too hasty.",
    exampleCn: "教育孩子不能揠苗助长。",
    examplePy: "Jiàoyù háizi bùnéng yà miáo zhù zhǎng.",
    exampleEn: "You can't rush a child's growth like pulling up seedlings.",
    tone: "R",
  },
  {
    idiom: "愚公移山",
    pinyin: "yú gōng yí shān",
    chars: [
      { c: "愚", p: "yú" },
      { c: "公", p: "gōng" },
      { c: "移", p: "yí" },
      { c: "山", p: "shān" },
    ],
    meaningCn: "比喻做事有毅力，坚持不懈，不怕困难。",
    meaningEn: "The Foolish Old Man who moved the mountains — perseverance against great odds.",
    exampleCn: "只要有愚公移山的精神，何愁不能成功？",
    examplePy: "Zhǐyào yǒu yú gōng yí shān de jīngshén, hé chóu bùnéng chénggōng?",
    exampleEn: "With the spirit of the Foolish Old Man, success is within reach.",
    tone: "G",
  },
  {
    idiom: "精卫填海",
    pinyin: "jīng wèi tián hǎi",
    chars: [
      { c: "精", p: "jīng" },
      { c: "卫", p: "wèi" },
      { c: "填", p: "tián" },
      { c: "海", p: "hǎi" },
    ],
    meaningCn: "比喻意志坚决，不畏艰难。",
    meaningEn: "The mythical bird Jingwei filling the sea — resolute in the face of difficulty.",
    exampleCn: "他以精卫填海的毅力坚持科研。",
    examplePy: "Tā yǐ jīng wèi tián hǎi de yìlì jiānchí kēyán.",
    exampleEn: "He persists in research with the resolve of Jingwei filling the sea.",
    tone: "R",
  },
  {
    idiom: "卧薪尝胆",
    pinyin: "wò xīn cháng dǎn",
    chars: [
      { c: "卧", p: "wò" },
      { c: "薪", p: "xīn" },
      { c: "尝", p: "cháng" },
      { c: "胆", p: "dǎn" },
    ],
    meaningCn: "形容人刻苦自励，发愤图强。",
    meaningEn: "To sleep on firewood and taste gall — to endure hardship for a goal.",
    exampleCn: "他卧薪尝胆十余年，终于东山再起。",
    examplePy: "Tā wò xīn cháng dǎn shí yú nián, zhōngyú dōngshān zàiqǐ.",
    exampleEn: "After years of grinding hardship, he staged a comeback.",
    tone: "G",
  },
  {
    idiom: "破釜沉舟",
    pinyin: "pò fǔ chén zhōu",
    chars: [
      { c: "破", p: "pò" },
      { c: "釜", p: "fǔ" },
      { c: "沉", p: "chén" },
      { c: "舟", p: "zhōu" },
    ],
    meaningCn: "把锅打破、把船凿沉。比喻下定决心，不留退路地干到底。",
    meaningEn: "To smash the pots and sink the boats — to burn one's boats, no turning back.",
    exampleCn: "他决定破釜沉舟，背水一战。",
    examplePy: "Tā juédìng pò fǔ chén zhōu, bèi shuǐ yī zhàn.",
    exampleEn: "He resolved to burn his boats and fight with his back to the wall.",
    tone: "R",
  },
  {
    idiom: "背水一战",
    pinyin: "bèi shuǐ yī zhàn",
    chars: [
      { c: "背", p: "bèi" },
      { c: "水", p: "shuǐ" },
      { c: "一", p: "yī" },
      { c: "战", p: "zhàn" },
    ],
    meaningCn: "背靠河水作战，后退无路。比喻面临绝境，为求生路而决一死战。",
    meaningEn: "To fight with one's back to the river — a last-ditch fight for survival.",
    exampleCn: "决赛我们已无退路，唯有背水一战。",
    examplePy: "Juésài wǒmen yǐ wú tuìlù, wéiyǒu bèi shuǐ yī zhàn.",
    exampleEn: "With no way back in the final, we must fight with our backs to the wall.",
    tone: "G",
  },
  {
    idiom: "望梅止渴",
    pinyin: "wàng méi zhǐ kě",
    chars: [
      { c: "望", p: "wàng" },
      { c: "梅", p: "méi" },
      { c: "止", p: "zhǐ" },
      { c: "渴", p: "kě" },
    ],
    meaningCn: "比喻愿望无法实现，用空想来安慰自己。",
    meaningEn: "To quench thirst by thinking of plums — to console oneself with fantasies.",
    exampleCn: "光计划不行动，无异于望梅止渴。",
    examplePy: "Guāng jìhuà bù xíngdòng, wúyì yú wàng méi zhǐ kě.",
    exampleEn: "Planning without acting is like quenching thirst by thinking of plums.",
    tone: "R",
  },
  {
    idiom: "三顾茅庐",
    pinyin: "sān gù máo lú",
    chars: [
      { c: "三", p: "sān" },
      { c: "顾", p: "gù" },
      { c: "茅", p: "máo" },
      { c: "庐", p: "lú" },
    ],
    meaningCn: "比喻真心诚意，一再邀请、拜访有专长的贤人。",
    meaningEn: "To visit the thatched hut three times — to sincerely court talent.",
    exampleCn: "他三顾茅庐，终于请到了这位专家。",
    examplePy: "Tā sān gù máo lú, zhōngyú qǐng dào le zhè wèi zhuānjiā.",
    exampleEn: "After three earnest visits, he finally won over the expert.",
    tone: "G",
  },
  {
    idiom: "完璧归赵",
    pinyin: "wán bì guī zhào",
    chars: [
      { c: "完", p: "wán" },
      { c: "璧", p: "bì" },
      { c: "归", p: "guī" },
      { c: "赵", p: "zhào" },
    ],
    meaningCn: "比喻把原物完好无损地归还本人。",
    meaningEn: "To return the jade intact to Zhao — to give back something unharmed.",
    exampleCn: "借你的书我完璧归赵，原样奉还。",
    examplePy: "Jiè nǐ de shū wǒ wán bì guī zhào, yuányàng fènghuán.",
    exampleEn: "I return your book intact, exactly as borrowed.",
    tone: "R",
  },
  {
    idiom: "负荆请罪",
    pinyin: "fù jīng qǐng zuì",
    chars: [
      { c: "负", p: "fù" },
      { c: "荆", p: "jīng" },
      { c: "请", p: "qǐng" },
      { c: "罪", p: "zuì" },
    ],
    meaningCn: "背着荆条上门请罪。表示主动认错赔罪，请求责罚。",
    meaningEn: "To carry brambles on one's back and ask for punishment — to offer a sincere apology.",
    exampleCn: "他登门负荆请罪，请求原谅。",
    examplePy: "Tā dēngmén fù jīng qǐng zuì, qǐngqiú yuánliàng.",
    exampleEn: "He came to apologize humbly, begging forgiveness.",
    tone: "G",
  },
  {
    idiom: "画龙点睛",
    pinyin: "huà lóng diǎn jīng",
    chars: [
      { c: "画", p: "huà" },
      { c: "龙", p: "lóng" },
      { c: "点", p: "diǎn" },
      { c: "睛", p: "jīng" },
    ],
    meaningCn: "在画好的龙上点上眼睛。比喻在关键处用几句话点明实质，使内容更生动有力。",
    meaningEn: "To add the pupil to the dragon — to add the finishing touch that brings it to life.",
    exampleCn: "结尾那句总结画龙点睛，让全文更有力。",
    examplePy: "Jiéwěi nà jù zǒngjié huà lóng diǎn jīng, ràng quánwén gèng yǒulì.",
    exampleEn: "The concluding remark is the finishing touch that brings the essay to life.",
    tone: "R",
  },
  {
    idiom: "胸有成竹",
    pinyin: "xiōng yǒu chéng zhú",
    chars: [
      { c: "胸", p: "xiōng" },
      { c: "有", p: "yǒu" },
      { c: "成", p: "chéng" },
      { c: "竹", p: "zhú" },
    ],
    meaningCn: "比喻在做事之前，已经有了通盘的考虑和把握。",
    meaningEn: "To have a bamboo in one's chest — to have a well-thought-out plan beforehand.",
    exampleCn: "他胸有成竹地迎接这场考试。",
    examplePy: "Tā xiōng yǒu chéng zhú de yíngjiē zhè chǎng kǎoshì.",
    exampleEn: "He faced the exam with complete confidence.",
    tone: "G",
  },
  {
    idiom: "一鸣惊人",
    pinyin: "yī míng jīng rén",
    chars: [
      { c: "一", p: "yī" },
      { c: "鸣", p: "míng" },
      { c: "惊", p: "jīng" },
      { c: "人", p: "rén" },
    ],
    meaningCn: "比喻平时没有特殊表现，一下子就做出了惊人的成绩。",
    meaningEn: "To astonish with a single cry — to amaze people all of a sudden.",
    exampleCn: "他首次参赛就一鸣惊人，夺得冠军。",
    examplePy: "Tā shǒucì cānsài jiù yī míng jīng rén, duódé guànjūn.",
    exampleEn: "In his first contest, he startled everyone by winning the championship.",
    tone: "R",
  },
  {
    idiom: "洛阳纸贵",
    pinyin: "luò yáng zhǐ guì",
    chars: [
      { c: "洛", p: "luò" },
      { c: "阳", p: "yáng" },
      { c: "纸", p: "zhǐ" },
      { c: "贵", p: "guì" },
    ],
    meaningCn: "比喻著作有价值，流传很广，人人争相阅读。",
    meaningEn: "Paper becomes expensive in Luoyang — a work so popular everyone copies it.",
    exampleCn: "这部小说风靡一时，洛阳纸贵。",
    examplePy: "Zhè bù xiǎoshuō fēngmí yīshí, luò yáng zhǐ guì.",
    exampleEn: "The novel was such a hit that its copies sold like hotcakes.",
    tone: "G",
  },
  {
    idiom: "水滴石穿",
    pinyin: "shuǐ dī shí chuān",
    chars: [
      { c: "水", p: "shuǐ" },
      { c: "滴", p: "dī" },
      { c: "石", p: "shí" },
      { c: "穿", p: "chuān" },
    ],
    meaningCn: "水不停地滴，能把石头穿透。比喻只要坚持不懈，事情就能成功。",
    meaningEn: "Dripping water hollows out stone — perseverance conquers all.",
    exampleCn: "只要持之以恒，终能水滴石穿。",
    examplePy: "Zhǐyào chí zhī yǐ héng, zhōng néng shuǐ dī shí chuān.",
    exampleEn: "With persistence, even stone is worn away by water.",
    tone: "R",
  },
  {
    idiom: "草木皆兵",
    pinyin: "cǎo mù jiē bīng",
    chars: [
      { c: "草", p: "cǎo" },
      { c: "木", p: "mù" },
      { c: "皆", p: "jiē" },
      { c: "兵", p: "bīng" },
    ],
    meaningCn: "把草木都当成敌兵。形容人在惊慌时疑神疑鬼。",
    meaningEn: "To see soldiers in every bush — to be paranoid in a panic.",
    exampleCn: "一有风吹草动，他就草木皆兵。",
    examplePy: "Yī yǒu fēngchuīcǎodòng, tā jiù cǎo mù jiē bīng.",
    exampleEn: "At the slightest sign of trouble, he gets spooked.",
    tone: "G",
  },
  {
    idiom: "举一反三",
    pinyin: "jǔ yī fǎn sān",
    chars: [
      { c: "举", p: "jǔ" },
      { c: "一", p: "yī" },
      { c: "反", p: "fǎn" },
      { c: "三", p: "sān" },
    ],
    meaningCn: "比喻善于由此及彼，触类旁通，学会一样就能推知更多。",
    meaningEn: "To draw three inferences from one example — to learn by analogy.",
    exampleCn: "他悟性很强，能举一反三。",
    examplePy: "Tā wùxìng hěn qiáng, néng jǔ yī fǎn sān.",
    exampleEn: "He's quick and learns by analogy.",
    tone: "R",
  },
  {
    idiom: "温故知新",
    pinyin: "wēn gù zhī xīn",
    chars: [
      { c: "温", p: "wēn" },
      { c: "故", p: "gù" },
      { c: "知", p: "zhī" },
      { c: "新", p: "xīn" },
    ],
    meaningCn: "温习旧知识，能得到新的理解和体会。",
    meaningEn: "To gain new insights by reviewing what one has learned.",
    exampleCn: "复习旧功课，往往能温故知新。",
    examplePy: "Fùxí jiù gōngkè, wǎngwǎng néng wēn gù zhī xīn.",
    exampleEn: "Reviewing old lessons often yields new understanding.",
    tone: "G",
  },
  {
    idiom: "闻鸡起舞",
    pinyin: "wén jī qǐ wǔ",
    chars: [
      { c: "闻", p: "wén" },
      { c: "鸡", p: "jī" },
      { c: "起", p: "qǐ" },
      { c: "舞", p: "wǔ" },
    ],
    meaningCn: "听到鸡叫就起来舞剑。形容有志之士及时奋发，刻苦自励。",
    meaningEn: "To rise and practice at the crow of the rooster — to be diligent and self-motivated.",
    exampleCn: "他闻鸡起舞，每天早起锻炼。",
    examplePy: "Tā wén jī qǐ wǔ, měitiān zǎoqǐ duànliàn.",
    exampleEn: "He rises with the rooster to train each morning.",
    tone: "R",
  },
  {
    idiom: "乘风破浪",
    pinyin: "chéng fēng pò làng",
    chars: [
      { c: "乘", p: "chéng" },
      { c: "风", p: "fēng" },
      { c: "破", p: "pò" },
      { c: "浪", p: "làng" },
    ],
    meaningCn: "比喻志向远大，不畏艰险，勇往直前。",
    meaningEn: "To ride the wind and break the waves — to forge ahead bravely.",
    exampleCn: "祝愿你们乘风破浪，前程似锦。",
    examplePy: "Zhùyuàn nǐmen chéng fēng pò làng, qiánchéng sìjǐn.",
    exampleEn: "May you ride the wind and waves to a bright future.",
    tone: "G",
  },
  {
    idiom: "锲而不舍",
    pinyin: "qiè ér bù shě",
    chars: [
      { c: "锲", p: "qiè" },
      { c: "而", p: "ér" },
      { c: "不", p: "bù" },
      { c: "舍", p: "shě" },
    ],
    meaningCn: "比喻有恒心、有毅力，坚持到底。",
    meaningEn: "To keep carving without giving up — to persevere.",
    exampleCn: "锲而不舍的学习，让他进步飞快。",
    examplePy: "Qiè ér bù shě de xuéxí, ràng tā jìnbù fēikuài.",
    exampleEn: "Persistent study made him improve rapidly.",
    tone: "R",
  },
  {
    idiom: "一丝不苟",
    pinyin: "yī sī bù gǒu",
    chars: [
      { c: "一", p: "yī" },
      { c: "丝", p: "sī" },
      { c: "不", p: "bù" },
      { c: "苟", p: "gǒu" },
    ],
    meaningCn: "形容办事认真，连最细微的地方也不马虎。",
    meaningEn: "To be scrupulous about every detail — meticulous.",
    exampleCn: "他对待工作一丝不苟，深受好评。",
    examplePy: "Tā duìdài gōngzuò yī sī bù gǒu, shēnshòu hǎopíng.",
    exampleEn: "He's meticulous in his work and well regarded for it.",
    tone: "G",
  },
  {
    idiom: "出类拔萃",
    pinyin: "chū lèi bá cuì",
    chars: [
      { c: "出", p: "chū" },
      { c: "类", p: "lèi" },
      { c: "拔", p: "bá" },
      { c: "萃", p: "cuì" },
    ],
    meaningCn: "形容超出同类，才能出众。",
    meaningEn: "To stand out from the crowd — to be outstanding.",
    exampleCn: "她才华出众，在同龄人中出类拔萃。",
    examplePy: "Tā cáihuá chūzhòng, zài tónglíngrén zhōng chū lèi bá cuì.",
    exampleEn: "Her talent is outstanding among her peers.",
    tone: "R",
  },
  {
    idiom: "持之以恒",
    pinyin: "chí zhī yǐ héng",
    chars: [
      { c: "持", p: "chí" },
      { c: "之", p: "zhī" },
      { c: "以", p: "yǐ" },
      { c: "恒", p: "héng" },
    ],
    meaningCn: "长久地坚持下去。",
    meaningEn: "To persist steadily over the long term.",
    exampleCn: "锻炼身体贵在持之以恒。",
    examplePy: "Duànliàn shēntǐ guì zài chí zhī yǐ héng.",
    exampleEn: "The key to exercise is consistency.",
    tone: "G",
  },
  {
    idiom: "专心致志",
    pinyin: "zhuān xīn zhì zhì",
    chars: [
      { c: "专", p: "zhuān" },
      { c: "心", p: "xīn" },
      { c: "致", p: "zhì" },
      { c: "志", p: "zhì" },
    ],
    meaningCn: "一心一意，集中全部精神。",
    meaningEn: "To devote oneself wholly to something — single-minded.",
    exampleCn: "他专心致志地投入研究。",
    examplePy: "Tā zhuān xīn zhì zhì de tóurù yánjiū.",
    exampleEn: "He devotes himself single-mindedly to research.",
    tone: "R",
  },
  {
    idiom: "画饼充饥",
    pinyin: "huà bǐng chōng jī",
    chars: [
      { c: "画", p: "huà" },
      { c: "饼", p: "bǐng" },
      { c: "充", p: "chōng" },
      { c: "饥", p: "jī" },
    ],
    meaningCn: "比喻用空想来安慰自己，不能解决实际问题。",
    meaningEn: "To draw a cake to satisfy hunger — to comfort oneself with empty promises.",
    exampleCn: "别用画饼充饥的计划来开空头支票。",
    examplePy: "Bié yòng huà bǐng chōng jī de jìhuà lái kāi kōngtóu zhīpiào.",
    exampleEn: "Don't make empty promises with pie-in-the-sky plans.",
    tone: "G",
  },
  {
    idiom: "触类旁通",
    pinyin: "chù lèi páng tōng",
    chars: [
      { c: "触", p: "chù" },
      { c: "类", p: "lèi" },
      { c: "旁", p: "páng" },
      { c: "通", p: "tōng" },
    ],
    meaningCn: "掌握了某一事物的规律，就能推知同类其他事物。",
    meaningEn: "To grasp one thing and understand the whole class — to reason by analogy.",
    exampleCn: "学会这个方法，便能触类旁通。",
    examplePy: "Xuéhuì zhège fāngfǎ, biàn néng chù lèi páng tōng.",
    exampleEn: "Learn the method and you can apply it to the whole category.",
    tone: "R",
  },
  {
    idiom: "磨杵成针",
    pinyin: "mó chǔ chéng zhēn",
    chars: [
      { c: "磨", p: "mó" },
      { c: "杵", p: "chǔ" },
      { c: "成", p: "chéng" },
      { c: "针", p: "zhēn" },
    ],
    meaningCn: "把铁杵磨成针。比喻只要有恒心、肯努力，再难的事也能做成。",
    meaningEn: "To grind an iron pestle into a needle — with perseverance nothing is impossible.",
    exampleCn: "只要功夫深，铁杵磨成针。",
    examplePy: "Zhǐyào gōngfu shēn, tiěchǔ mó chéng zhēn.",
    exampleEn: "With enough effort, even an iron pestle becomes a needle.",
    tone: "G",
  },
  {
    idiom: "才高八斗",
    pinyin: "cái gāo bā dǒu",
    chars: [
      { c: "才", p: "cái" },
      { c: "高", p: "gāo" },
      { c: "八", p: "bā" },
      { c: "斗", p: "dǒu" },
    ],
    meaningCn: "形容文才极高。",
    meaningEn: "To have eight dou of talent — extremely gifted in letters.",
    exampleCn: "他年纪轻轻便才高八斗，令人佩服。",
    examplePy: "Tā niánjì qīngqīng biàn cái gāo bā dǒu, lìngrén pèifú.",
    exampleEn: "Young as he is, his brilliance is admirable.",
    tone: "R",
  },
  {
    idiom: "程门立雪",
    pinyin: "chéng mén lì xuě",
    chars: [
      { c: "程", p: "chéng" },
      { c: "门", p: "mén" },
      { c: "立", p: "lì" },
      { c: "雪", p: "xuě" },
    ],
    meaningCn: "在程颐门前站到雪里。形容尊师重道，恭敬求教。",
    meaningEn: "To stand in the snow at the master's door — to show utmost respect for learning.",
    exampleCn: "他程门立雪般的恭敬，感动了老师。",
    examplePy: "Tā chéng mén lì xuě bān de gōngjìng, gǎndòng le lǎoshī.",
    exampleEn: "His reverent attitude touched the teacher.",
    tone: "G",
  },
];
