// 扩充成语库 · 批次 3（追加到 IDIOMS）
IDIOMS = IDIOMS.concat([
  { idiom:"马到成功", pinyin:"mǎ dào chéng gōng", chars:[{c:"马",p:"mǎ"},{c:"到",p:"dào"},{c:"成",p:"chéng"},{c:"功",p:"gōng"}],
    meaningCn:"战马一到就取胜。比喻事情顺利，很快取得成功。", meaningEn:"To win immediately; to succeed at once.",
    exampleCn:"祝你首战告捷，马到成功！", examplePy:"Zhù nǐ shǒuzhàn gàojié, mǎ dào chéng gōng!", exampleEn:"Wishing you instant success!", tone:"G" },
  { idiom:"旗开得胜", pinyin:"qí kāi dé shèng", chars:[{c:"旗",p:"qí"},{c:"开",p:"kāi"},{c:"得",p:"dé"},{c:"胜",p:"shèng"}],
    meaningCn:"旗帜一展开就打了胜仗。比喻事情一开头就取得好成绩。", meaningEn:"To win on the first try; to score an early victory.",
    exampleCn:"比赛旗开得胜，士气大振。", examplePy:"Bǐsài qí kāi dé shèng, shìqì dàzhèn.", exampleEn:"They won early and morale soared.", tone:"G" },
  { idiom:"一帆风顺", pinyin:"yī fān fēng shùn", chars:[{c:"一",p:"yī"},{c:"帆",p:"fān"},{c:"风",p:"fēng"},{c:"顺",p:"shùn"}],
    meaningCn:"船挂满帆，顺风而行。比喻非常顺利，没有阻碍。", meaningEn:"Plain sailing; to go smoothly without hindrance.",
    exampleCn:"祝你考试一帆风顺，取得好成绩。", examplePy:"Zhù nǐ kǎoshì yī fān fēng shùn, qǔdé hǎo chéngjì.", exampleEn:"Wishing you smooth sailing on your exam.", tone:"G" },
  { idiom:"万事如意", pinyin:"wàn shì rú yì", chars:[{c:"万",p:"wàn"},{c:"事",p:"shì"},{c:"如",p:"rú"},{c:"意",p:"yì"}],
    meaningCn:"一切都符合心意。指诸事顺利。", meaningEn:"May everything go as one wishes.",
    exampleCn:"新春快乐，万事如意！", examplePy:"Xīnchūn kuàilè, wàn shì rú yì!", exampleEn:"Happy New Year, may all go well!", tone:"G" },
  { idiom:"心想事成", pinyin:"xīn xiǎng shì chéng", chars:[{c:"心",p:"xīn"},{c:"想",p:"xiǎng"},{c:"事",p:"shì"},{c:"成",p:"chéng"}],
    meaningCn:"心里想到的，都能做成。祝福人愿望实现。", meaningEn:"May your wishes come true.",
    exampleCn:"愿你心想事成，梦想成真。", examplePy:"Yuàn nǐ xīn xiǎng shì chéng, mèngxiǎng chéngzhēn.", exampleEn:"May your dreams come true.", tone:"G" },
  { idiom:"前程似锦", pinyin:"qián chéng sì jǐn", chars:[{c:"前",p:"qián"},{c:"程",p:"chéng"},{c:"似",p:"sì"},{c:"锦",p:"jǐn"}],
    meaningCn:"前程像锦绣一样美好。形容前途十分光明。", meaningEn:"A bright future; prospects as beautiful as brocade.",
    exampleCn:"祝你们前程似锦，鹏程万里。", examplePy:"Zhù nǐmen qián chéng sì jǐn, péngchéng wànlǐ.", exampleEn:"Wishing you a bright and boundless future.", tone:"G" },
  { idiom:"大展宏图", pinyin:"dà zhǎn hóng tú", chars:[{c:"大",p:"dà"},{c:"展",p:"zhǎn"},{c:"宏",p:"hóng"},{c:"图",p:"tú"}],
    meaningCn:"大力施展宏伟的抱负。", meaningEn:"To carry out one's grand plans; to realize great ambitions.",
    exampleCn:"祝你在新岗位上大展宏图。", examplePy:"Zhù nǐ zài xīn gǎngwèi shàng dà zhǎn hóng tú.", exampleEn:"Wishing you great success in your new role.", tone:"G" },
  { idiom:"众志成城", pinyin:"zhòng zhì chéng chéng", chars:[{c:"众",p:"zhòng"},{c:"志",p:"zhì"},{c:"成",p:"chéng"},{c:"城",p:"chéng"}],
    meaningCn:"万众一心，像坚固的城墙一样。比喻团结一致，力量无比强大。", meaningEn:"Unity is strength; united we stand like a wall.",
    exampleCn:"只要众志成城，没有克服不了的困难。", examplePy:"Zhǐyào zhòng zhì chéng chéng, méiyǒu kèfú bùliǎo de kùnnan.", exampleEn:"With unity, no difficulty is insurmountable.", tone:"G" },
  { idiom:"齐心协力", pinyin:"qí xīn xié lì", chars:[{c:"齐",p:"qí"},{c:"心",p:"xīn"},{c:"协",p:"xié"},{c:"力",p:"lì"}],
    meaningCn:"大家同心，共同努力。", meaningEn:"To work together with one heart.",
    exampleCn:"大家齐心协力，圆满完成任务。", examplePy:"Dàjiā qí xīn xié lì, yuánmǎn wánchéng rènwu.", exampleEn:"Everyone pulled together and finished the job.", tone:"G" },
  { idiom:"集思广益", pinyin:"jí sī guǎng yì", chars:[{c:"集",p:"jí"},{c:"思",p:"sī"},{c:"广",p:"guǎng"},{c:"益",p:"yì"}],
    meaningCn:"集中众人的意见和智慧，能得到更好的效果。", meaningEn:"To pool the wisdom of the many; to benefit from group ideas.",
    exampleCn:"开会就是集思广益，博采众长。", examplePy:"Kāihuì jiùshì jí sī guǎng yì, bócǎi zhòngcháng.", exampleEn:"Meetings pool everyone's ideas.", tone:"G" },
  { idiom:"取长补短", pinyin:"qǔ cháng bǔ duǎn", chars:[{c:"取",p:"qǔ"},{c:"长",p:"cháng"},{c:"补",p:"bǔ"},{c:"短",p:"duǎn"}],
    meaningCn:"吸取别人的长处，弥补自己的短处。", meaningEn:"To learn from others' strengths to cover one's weaknesses.",
    exampleCn:"同学之间要互相取长补短。", examplePy:"Tóngxué zhījiān yào hùxiāng qǔ cháng bǔ duǎn.", exampleEn:"Classmates should learn from each other.", tone:"G" },
  { idiom:"扬长避短", pinyin:"yáng cháng bì duǎn", chars:[{c:"扬",p:"yáng"},{c:"长",p:"cháng"},{c:"避",p:"bì"},{c:"短",p:"duǎn"}],
    meaningCn:"发挥长处，避开短处。", meaningEn:"To play to one's strengths and avoid weaknesses.",
    exampleCn:"用人要扬长避短，人尽其才。", examplePy:"Yòngrén yào yáng cháng bì duǎn, rén jìn qí cái.", exampleEn:"Use people's strengths and avoid their weaknesses.", tone:"G" },
  { idiom:"精益求精", pinyin:"jīng yì qiú jīng", chars:[{c:"精",p:"jīng"},{c:"益",p:"yì"},{c:"求",p:"qiú"},{c:"精",p:"jīng"}],
    meaningCn:"已经很好了，还要求更好。形容追求完美。", meaningEn:"To strive for perfection; to keep improving.",
    exampleCn:"他对产品精益求精，从不将就。", examplePy:"Tā duì chǎnpǐn jīng yì qiú jīng, cóngbù jiāngjiu.", exampleEn:"He perfects every detail, never settling.", tone:"G" },
  { idiom:"炉火纯青", pinyin:"lú huǒ chún qīng", chars:[{c:"炉",p:"lú"},{c:"火",p:"huǒ"},{c:"纯",p:"chún"},{c:"青",p:"qīng"}],
    meaningCn:"炉火发出纯青的火光。比喻技术或学问达到纯熟完美的境界。", meaningEn:"To reach the acme of perfection; to be at one's peak.",
    exampleCn:"他的书法已炉火纯青。", examplePy:"Tā de shūfǎ yǐ lú huǒ chún qīng.", exampleEn:"His calligraphy has reached perfection.", tone:"G" },
  { idiom:"登峰造极", pinyin:"dēng fēng zào jí", chars:[{c:"登",p:"dēng"},{c:"峰",p:"fēng"},{c:"造",p:"zào"},{c:"极",p:"jí"}],
    meaningCn:"登上顶峰，达到极点。比喻达到最高的水平。", meaningEn:"To reach the summit; to attain the highest level.",
    exampleCn:"她的厨艺登峰造极，令人叹服。", examplePy:"Tā de chúyì dēng fēng zào jí, lìngrén tànfú.", exampleEn:"Her cooking is at its absolute peak.", tone:"G" },
  { idiom:"出神入化", pinyin:"chū shén rù huà", chars:[{c:"出",p:"chū"},{c:"神",p:"shén"},{c:"入",p:"rù"},{c:"化",p:"huà"}],
    meaningCn:"超出神妙，进入化境。形容技艺达到了绝妙的境界。", meaningEn:"To reach the realm of the divine; to be superb.",
    exampleCn:"他的演奏出神入化，扣人心弦。", examplePy:"Tā de yǎnzòu chū shén rù huà, kòurénxīnxián.", exampleEn:"His performance was breathtakingly superb.", tone:"G" },
  { idiom:"鬼斧神工", pinyin:"guǐ fǔ shén gōng", chars:[{c:"鬼",p:"guǐ"},{c:"斧",p:"fǔ"},{c:"神",p:"shén"},{c:"工",p:"gōng"}],
    meaningCn:"像是鬼神制作出来的。形容建筑、雕塑等技艺精巧，太不平凡。", meaningEn:"Supernatural craftsmanship; works of exquisite skill.",
    exampleCn:"这座石雕鬼斧神工，令人惊叹。", examplePy:"Zhè zuò shídiāo guǐ fǔ shén gōng, lìngrén jīngtàn.", exampleEn:"The stone carving is astonishingly skillful.", tone:"G" },
  { idiom:"巧夺天工", pinyin:"qiǎo duó tiān gōng", chars:[{c:"巧",p:"qiǎo"},{c:"夺",p:"duó"},{c:"天",p:"tiān"},{c:"工",p:"gōng"}],
    meaningCn:"精巧胜过天然。形容人工技艺非常高超。", meaningEn:"To outdo nature; exquisite workmanship.",
    exampleCn:"这件工艺品巧夺天工。", examplePy:"Zhè jiàn gōngyìpǐn qiǎo duó tiān gōng.", exampleEn:"This craft piece rivals nature itself.", tone:"G" },
  { idiom:"独具匠心", pinyin:"dú jù jiàng xīn", chars:[{c:"独",p:"dú"},{c:"具",p:"jù"},{c:"匠",p:"jiàng"},{c:"心",p:"xīn"}],
    meaningCn:"具有独到的巧思。形容在技巧和艺术方面有独创性。", meaningEn:"To show original ingenuity.",
    exampleCn:"这个设计独具匠心，令人眼前一亮。", examplePy:"Zhège shèjì dú jù jiàng xīn, lìngrén yǎnguāng yí liàng.", exampleEn:"The design is ingeniously original.", tone:"G" },
  { idiom:"别具一格", pinyin:"bié jù yī gé", chars:[{c:"别",p:"bié"},{c:"具",p:"jù"},{c:"一",p:"yī"},{c:"格",p:"gé"}],
    meaningCn:"另有一种独特的风格。", meaningEn:"To have a distinctive style of one's own.",
    exampleCn:"他的画风别具一格，很有个性。", examplePy:"Tā de huàfēng bié jù yī gé, hěn yǒu gèxìng.", exampleEn:"His painting style is uniquely original.", tone:"G" },
  { idiom:"独树一帜", pinyin:"dú shù yī zhì", chars:[{c:"独",p:"dú"},{c:"树",p:"shù"},{c:"一",p:"yī"},{c:"帜",p:"zhì"}],
    meaningCn:"单独树立一面旗帜。比喻自成一家，有独特风格。", meaningEn:"To develop one's own school or style.",
    exampleCn:"他在乐坛独树一帜。", examplePy:"Tā zài yuètán dú shù yī zhì.", exampleEn:"He stands alone in the music world.", tone:"G" },
  { idiom:"标新立异", pinyin:"biāo xīn lì yì", chars:[{c:"标",p:"biāo"},{c:"新",p:"xīn"},{c:"立",p:"lì"},{c:"异",p:"yì"}],
    meaningCn:"提出新奇的主张，表示与众不同。", meaningEn:"To be unconventional; to blaze a new trail.",
    exampleCn:"创新就要敢于标新立异。", examplePy:"Chuàngxīn jiù yào gǎnyú biāo xīn lì yì.", exampleEn:"Innovation requires daring to be unconventional.", tone:"G" },
  { idiom:"与众不同", pinyin:"yǔ zhòng bù tóng", chars:[{c:"与",p:"yǔ"},{c:"众",p:"zhòng"},{c:"不",p:"bù"},{c:"同",p:"tóng"}],
    meaningCn:"跟众人不一样。形容有特色。", meaningEn:"To be distinctive; out of the ordinary.",
    exampleCn:"她衣着的品味与众不同。", examplePy:"Tā yīzhuó de pǐnwèi yǔ zhòng bù tóng.", exampleEn:"Her taste in clothes is out of the ordinary.", tone:"G" },
  { idiom:"别出心裁", pinyin:"bié chū xīn cái", chars:[{c:"别",p:"bié"},{c:"出",p:"chū"},{c:"心",p:"xīn"},{c:"裁",p:"cái"}],
    meaningCn:"另想出一种与众不同的新主意。", meaningEn:"To hit on something novel; to be original.",
    exampleCn:"这幅海报别出心裁，很吸引人。", examplePy:"Zhè fú hǎibào bié chū xīn cái, hěn xīyǐnrén.", exampleEn:"The poster is original and eye-catching.", tone:"G" },
  { idiom:"妙笔生花", pinyin:"miào bǐ shēng huā", chars:[{c:"妙",p:"miào"},{c:"笔",p:"bǐ"},{c:"生",p:"shēng"},{c:"花",p:"huā"}],
    meaningCn:"形容写作技巧非常高超，文字优美。", meaningEn:"To write with brilliant style; a gifted pen.",
    exampleCn:"他妙笔生花，把故事写得栩栩如生。", examplePy:"Tā miào bǐ shēng huā, bǎ gùshi xiě de xǔxǔ rú shēng.", exampleEn:"His brilliant writing brings the story to life.", tone:"G" },
  { idiom:"行云流水", pinyin:"xíng yún liú shuǐ", chars:[{c:"行",p:"xíng"},{c:"云",p:"yún"},{c:"流",p:"liú"},{c:"水",p:"shuǐ"}],
    meaningCn:"像飘动的云和流动的水。形容文章或艺术自然流畅。", meaningEn:"Flowing like clouds and water; natural and smooth.",
    exampleCn:"她的演讲行云流水，十分自然。", examplePy:"Tā de yǎnjiǎng xíng yún liú shuǐ, shífēn zìrán.", exampleEn:"Her speech flowed naturally and smoothly.", tone:"G" },
  { idiom:"挥洒自如", pinyin:"huī sǎ zì rú", chars:[{c:"挥",p:"huī"},{c:"洒",p:"sǎ"},{c:"自",p:"zì"},{c:"如",p:"rú"}],
    meaningCn:"形容写字、作画或行文运笔自然流畅，毫无拘束。", meaningEn:"To write or paint with effortless ease.",
    exampleCn:"他画画挥洒自如，一气呵成。", examplePy:"Tā huàhuà huī sǎ zì rú, yī qì hē chéng.", exampleEn:"He paints with effortless fluency.", tone:"G" },
  { idiom:"游刃有余", pinyin:"yóu rèn yǒu yú", chars:[{c:"游",p:"yóu"},{c:"刃",p:"rèn"},{c:"有",p:"yǒu"},{c:"余",p:"yú"}],
    meaningCn:"刀刃在骨节间运转，还很宽裕。形容技术熟练，解决问题毫不费力。", meaningEn:"To handle things with ease and skill.",
    exampleCn:"处理这类问题，他游刃有余。", examplePy:"Chǔlǐ zhè lèi wèntí, tā yóu rèn yǒu yú.", exampleEn:"He handles such problems with ease.", tone:"G" },
  { idiom:"得心应手", pinyin:"dé xīn yìng shǒu", chars:[{c:"得",p:"dé"},{c:"心",p:"xīn"},{c:"应",p:"yìng"},{c:"手",p:"shǒu"}],
    meaningCn:"心里怎么想，手就能怎么做。形容运用自如。", meaningEn:"To do with great facility; handy and effortless.",
    exampleCn:"多练几次，操作自然得心应手。", examplePy:"Duō liàn jǐ cì, cāozuò zìrán dé xīn yìng shǒu.", exampleEn:"Practice makes the operation effortless.", tone:"G" },
  { idiom:"驾轻就熟", pinyin:"jià qīng jiù shú", chars:[{c:"驾",p:"jià"},{c:"轻",p:"qīng"},{c:"就",p:"jiù"},{c:"熟",p:"shú"}],
    meaningCn:"驾着轻车走熟路。比喻对事情熟悉，做起来轻松。", meaningEn:"To do something familiar with ease.",
    exampleCn:"这项工作对他来说驾轻就熟。", examplePy:"Zhè xiàng gōngzuò duì tā lái shuō jià qīng jiù shú.", exampleEn:"This task is a walk in the park for him.", tone:"G" },
  { idiom:"熟能生巧", pinyin:"shú néng shēng qiǎo", chars:[{c:"熟",p:"shú"},{c:"能",p:"néng"},{c:"生",p:"shēng"},{c:"巧",p:"qiǎo"}],
    meaningCn:"熟练了就能产生巧办法。", meaningEn:"Practice makes perfect.",
    exampleCn:"别怕，熟能生巧，练练就会了。", examplePy:"Bié pà, shú néng shēng qiǎo, liànliàn jiù huì le.", exampleEn:"Don't worry — practice makes perfect.", tone:"G" },
  { idiom:"勤能补拙", pinyin:"qín néng bǔ zhuō", chars:[{c:"勤",p:"qín"},{c:"能",p:"néng"},{c:"补",p:"bǔ"},{c:"拙",p:"zhuō"}],
    meaningCn:"勤奋能够弥补天赋不足。", meaningEn:"Diligence can make up for lack of talent.",
    exampleCn:"勤能补拙，只要你肯下功夫。", examplePy:"Qín néng bǔ zhuō, zhǐyào nǐ kěn xià gōngfu.", exampleEn:"Diligence compensates for inborn weakness.", tone:"G" },
  { idiom:"笨鸟先飞", pinyin:"bèn niǎo xiān fēi", chars:[{c:"笨",p:"bèn"},{c:"鸟",p:"niǎo"},{c:"先",p:"xiān"},{c:"飞",p:"fēi"}],
    meaningCn:"能力差的人，做事比别人先行动。比喻用勤奋来弥补不足。", meaningEn:"The slow bird must start early — to compensate by diligence.",
    exampleCn:"我笨鸟先飞，提前开始准备。", examplePy:"Wǒ bèn niǎo xiān fēi, tíqián kāishǐ zhǔnbèi.", exampleEn:"I start early to make up for being slow.", tone:"G" },
  { idiom:"后来居上", pinyin:"hòu lái jū shàng", chars:[{c:"后",p:"hòu"},{c:"来",p:"lái"},{c:"居",p:"jū"},{c:"上",p:"shàng"}],
    meaningCn:"后来的人或事物超过了先前的。", meaningEn:"The latecomer overtakes the earlier ones.",
    exampleCn:"他后来居上，成为团队里的佼佼者。", examplePy:"Tā hòu lái jū shàng, chéngwéi tuánduì lǐ de jiǎojiǎozhě.", exampleEn:"He rose from behind to be the standout.", tone:"G" },
  { idiom:"迎头赶上", pinyin:"yíng tóu gǎn shàng", chars:[{c:"迎",p:"yíng"},{c:"头",p:"tóu"},{c:"赶",p:"gǎn"},{c:"上",p:"shàng"}],
    meaningCn:"迎上前去，努力赶上别人。", meaningEn:"To catch up from behind; to face and overtake.",
    exampleCn:"落后并不可怕，关键要迎头赶上。", examplePy:"Luòhòu bìng bù kěpà, guānjiàn yào yíng tóu gǎn shàng.", exampleEn:"Falling behind isn't scary; catching up matters.", tone:"G" },
  { idiom:"奋起直追", pinyin:"fèn qǐ zhí zhuī", chars:[{c:"奋",p:"fèn"},{c:"起",p:"qǐ"},{c:"直",p:"zhí"},{c:"追",p:"zhuī"}],
    meaningCn:"振作起来，努力追赶。", meaningEn:"To resolve to catch up; to strive forward.",
    exampleCn:"他决心奋起直追，迎头赶上。", examplePy:"Tā juéxīn fèn qǐ zhí zhuī, yíng tóu gǎn shàng.", exampleEn:"He resolved to press ahead and catch up.", tone:"G" },
  { idiom:"争先恐后", pinyin:"zhēng xiān kǒng hòu", chars:[{c:"争",p:"zhēng"},{c:"先",p:"xiān"},{c:"恐",p:"kǒng"},{c:"后",p:"hòu"}],
    meaningCn:"争着向前，唯恐落后。", meaningEn:"To vie to be first and dread being last.",
    exampleCn:"大家争先恐后地报名参加。", examplePy:"Dàjiā zhēng xiān kǒng hòu de bàomíng cānjiā.", exampleEn:"Everyone rushed to sign up.", tone:"G" },
  { idiom:"力争上游", pinyin:"lì zhēng shàng yóu", chars:[{c:"力",p:"lì"},{c:"争",p:"zhēng"},{c:"上",p:"shàng"},{c:"游",p:"yóu"}],
    meaningCn:"努力争取先进。", meaningEn:"To strive for the top; to aim high.",
    exampleCn:"全队力争上游，勇夺桂冠。", examplePy:"Quánduì lì zhēng shàng yóu, yǒng duó guìguān.", exampleEn:"The team strives for the top and wins.", tone:"G" },
  { idiom:"百尺竿头", pinyin:"bǎi chǐ gān tóu", chars:[{c:"百",p:"bǎi"},{c:"尺",p:"chǐ"},{c:"竿",p:"gān"},{c:"头",p:"tóu"}],
    meaningCn:"百尺高的竿子顶端。比喻学问、事业达到很高境界后还需更进一步。", meaningEn:"To go from the 100-foot pole one step further — to keep improving.",
    exampleCn:"成绩已很好，仍要百尺竿头，更进一步。", examplePy:"Chéngjì yǐ hěn hǎo, réng yào bǎi chǐ gān tóu, gèng jìn yí bù.", exampleEn:"Even at the top, keep pushing further.", tone:"G" },
  { idiom:"博古通今", pinyin:"bó gǔ tōng jīn", chars:[{c:"博",p:"bó"},{c:"古",p:"gǔ"},{c:"通",p:"tōng"},{c:"今",p:"jīn"}],
    meaningCn:"通晓古今的事情。形容知识渊博。", meaningEn:"To be learned in both ancient and modern matters.",
    exampleCn:"这位学者博古通今，令人敬佩。", examplePy:"Zhè wèi xuézhě bó gǔ tōng jīn, lìngrén jìngpèi.", exampleEn:"The scholar is deeply learned and admirable.", tone:"G" },
  { idiom:"学贯中西", pinyin:"xué guàn zhōng xī", chars:[{c:"学",p:"xué"},{c:"贯",p:"guàn"},{c:"中",p:"zhōng"},{c:"西",p:"xī"}],
    meaningCn:"学问贯通中国和西方。形容知识广博。", meaningEn:"To be learned in both Chinese and Western scholarship.",
    exampleCn:"他学贯中西，视野开阔。", examplePy:"Tā xué guàn zhōng xī, shìyě kāikuò.", exampleEn:"His learning spans East and West.", tone:"G" },
  { idiom:"博览群书", pinyin:"bó lǎn qún shū", chars:[{c:"博",p:"bó"},{c:"览",p:"lǎn"},{c:"群",p:"qún"},{c:"书",p:"shū"}],
    meaningCn:"广泛地阅读各种书籍。形容读书很多。", meaningEn:"To read widely; to be well-read.",
    exampleCn:"他博览群书，见多识广。", examplePy:"Tā bó lǎn qún shū, jiàn duō shí guǎng.", exampleEn:"He reads widely and is well informed.", tone:"G" },
  { idiom:"手不释卷", pinyin:"shǒu bù shì juàn", chars:[{c:"手",p:"shǒu"},{c:"不",p:"bù"},{c:"释",p:"shì"},{c:"卷",p:"juàn"}],
    meaningCn:"手里的书舍不得放下。形容读书勤奋。", meaningEn:"To never put a book down; to be devoted to reading.",
    exampleCn:"他手不释卷，废寝忘食。", examplePy:"Tā shǒu bù shì juàn, fèi qǐn wàng shí.", exampleEn:"He never puts his book down.", tone:"G" },
  { idiom:"孜孜不倦", pinyin:"zī zī bù juàn", chars:[{c:"孜",p:"zī"},{c:"孜",p:"zī"},{c:"不",p:"bù"},{c:"倦",p:"juàn"}],
    meaningCn:"勤奋努力，不知疲倦。", meaningEn:"To be tireless and diligent.",
    exampleCn:"他孜孜不倦地钻研学问。", examplePy:"Tā zī zī bù juàn de zuānyán xuéwèn.", exampleEn:"He studies diligently without tiring.", tone:"G" },
  { idiom:"废寝忘食", pinyin:"fèi qǐn wàng shí", chars:[{c:"废",p:"fèi"},{c:"寝",p:"qǐn"},{c:"忘",p:"wàng"},{c:"食",p:"shí"}],
    meaningCn:"顾不上睡觉，忘了吃饭。形容非常专心努力。", meaningEn:"To forget to eat and sleep; to be absorbed in work.",
    exampleCn:"他废寝忘食地赶项目。", examplePy:"Tā fèi qǐn wàng shí de gǎn xiàngmù.", exampleEn:"He works day and night on the project.", tone:"G" },
  { idiom:"夜以继日", pinyin:"yè yǐ jì rì", chars:[{c:"夜",p:"yè"},{c:"以",p:"yǐ"},{c:"继",p:"jì"},{c:"日",p:"rì"}],
    meaningCn:"用夜晚接上白天。形容日夜不停地工作。", meaningEn:"To work day and night; to keep at it around the clock.",
    exampleCn:"团队夜以继日地攻关。", examplePy:"Tuánduì yè yǐ jì rì de gōngguān.", exampleEn:"The team toils day and night on the breakthrough.", tone:"G" },
  { idiom:"兢兢业业", pinyin:"jīng jīng yè yè", chars:[{c:"兢",p:"jīng"},{c:"兢",p:"jīng"},{c:"业",p:"yè"},{c:"业",p:"yè"}],
    meaningCn:"做事小心谨慎，认真负责。", meaningEn:"To be conscientious and diligent.",
    exampleCn:"他兢兢业业，深受信任。", examplePy:"Tā jīng jīng yè yè, shēnshòu xìnrèn.", exampleEn:"He works diligently and is trusted.", tone:"G" },
  { idiom:"恪尽职守", pinyin:"kè jìn zhí shǒu", chars:[{c:"恪",p:"kè"},{c:"尽",p:"jìn"},{c:"职",p:"zhí"},{c:"守",p:"shǒu"}],
    meaningCn:"谨慎认真地做好本职工作。", meaningEn:"To faithfully discharge one's duties.",
    exampleCn:"他恪尽职守，从不懈怠。", examplePy:"Tā kè jìn zhí shǒu, cóngbù xièdài.", exampleEn:"He stays true to his duties, never remiss.", tone:"G" },
  { idiom:"任劳任怨", pinyin:"rèn láo rèn yuàn", chars:[{c:"任",p:"rèn"},{c:"劳",p:"láo"},{c:"任",p:"rèn"},{c:"怨",p:"yuàn"}],
    meaningCn:"不怕辛苦，也不埋怨。", meaningEn:"To work hard without complaint.",
    exampleCn:"她任劳任怨，是团队的中坚。", examplePy:"Tā rèn láo rèn yuàn, shì tuánduì de zhōngjiān.", exampleEn:"She works hard without a word of complaint.", tone:"G" },
  { idiom:"全力以赴", pinyin:"quán lì yǐ fù", chars:[{c:"全",p:"quán"},{c:"力",p:"lì"},{c:"以",p:"yǐ"},{c:"赴",p:"fù"}],
    meaningCn:"把全部力量都投入进去。", meaningEn:"To go all out; to devote every effort.",
    exampleCn:"我们要全力以赴，迎接挑战。", examplePy:"Wǒmen yào quán lì yǐ fù, yíngjiē tiǎozhàn.", exampleEn:"Let's go all out to meet the challenge.", tone:"G" },
  { idiom:"尽善尽美", pinyin:"jìn shàn jìn měi", chars:[{c:"尽",p:"jìn"},{c:"善",p:"shàn"},{c:"尽",p:"jìn"},{c:"美",p:"měi"}],
    meaningCn:"达到极其完善、极其美好的地步。", meaningEn:"To be perfect and flawless.",
    exampleCn:"这个方案尽善尽美，无可挑剔。", examplePy:"Zhège fāng'àn jìn shàn jìn měi, wúkě tiāotī.", exampleEn:"The plan is flawless.", tone:"G" },
  { idiom:"锦上添花", pinyin:"jǐn shàng tiān huā", chars:[{c:"锦",p:"jǐn"},{c:"上",p:"shàng"},{c:"添",p:"tiān"},{c:"花",p:"huā"}],
    meaningCn:"在织锦上再绣花。比喻好上加好，美上加美。", meaningEn:"To add flowers to brocade — to make a good thing even better.",
    exampleCn:"开幕式已经精彩，再加演出就是锦上添花。", examplePy:"Kāimùshì yǐjīng jīngcǎi, zài jiā yǎnchū jiùshì jǐn shàng tiān huā.", exampleEn:"The opening was great; a concert makes it even better.", tone:"G" },
  { idiom:"雪中送炭", pinyin:"xuě zhōng sòng tàn", chars:[{c:"雪",p:"xuě"},{c:"中",p:"zhōng"},{c:"送",p:"sòng"},{c:"炭",p:"tàn"}],
    meaningCn:"下雪天给人送炭取暖。比喻在别人急需时给予帮助。", meaningEn:"To send charcoal in snowy weather — help in time of need.",
    exampleCn:"这笔资助真是雪中送炭。", examplePy:"Zhè bǐ zīzhù zhēnshi xuě zhōng sòng tàn.", exampleEn:"This funding is truly timely help.", tone:"G" },
  { idiom:"如虎添翼", pinyin:"rú hǔ tiān yì", chars:[{c:"如",p:"rú"},{c:"虎",p:"hǔ"},{c:"添",p:"tiān"},{c:"翼",p:"yì"}],
    meaningCn:"像老虎添上了翅膀。比喻强者得到帮助后更加强大。", meaningEn:"To give wings to a tiger — to make the strong even stronger.",
    exampleCn:"有了新设备，团队如虎添翼。", examplePy:"Yǒu le xīn shèbèi, tuánduì rú hǔ tiān yì.", exampleEn:"With new equipment, the team is even stronger.", tone:"G" },
]);
