// 扩充成语库 · 批次 2（追加到 IDIOMS）
IDIOMS = IDIOMS.concat([
  { idiom:"三心二意", pinyin:"sān xīn èr yì", chars:[{c:"三",p:"sān"},{c:"心",p:"xīn"},{c:"二",p:"èr"},{c:"意",p:"yì"}],
    meaningCn:"心里想这样又想那样。形容犹豫不决或用心不专一。", meaningEn:"Of two minds; to be indecisive or half-hearted.",
    exampleCn:"做事不能三心二意，要专注才能做好。", examplePy:"Zuòshì bùnéng sān xīn èr yì, yào zhuānzhù cái néng zuòhǎo.", exampleEn:"Don't be half-hearted; focus to get things done.", tone:"G" },
  { idiom:"一心一意", pinyin:"yī xīn yī yì", chars:[{c:"一",p:"yī"},{c:"心",p:"xīn"},{c:"一",p:"yī"},{c:"意",p:"yì"}],
    meaningCn:"只有一个心眼儿，没有别的想法。形容专心致志。", meaningEn:"Wholeheartedly; single-minded devotion.",
    exampleCn:"他一心一意钻研学问，心无旁骛。", examplePy:"Tā yī xīn yī yì zuānyán xuéwèn, xīn wú páng wù.", exampleEn:"He devotes himself wholly to scholarship.", tone:"G" },
  { idiom:"半途而废", pinyin:"bàn tú ér fèi", chars:[{c:"半",p:"bàn"},{c:"途",p:"tú"},{c:"而",p:"ér"},{c:"废",p:"fèi"}],
    meaningCn:"半路上就停下来，不再前进。比喻做事有始无终。", meaningEn:"To give up halfway; to leave a job unfinished.",
    exampleCn:"既然开始了，就不要半途而废。", examplePy:"Jìrán kāishǐ le, jiù búyào bàn tú ér fèi.", exampleEn:"Once you start, don't give up halfway.", tone:"R" },
  { idiom:"坚持不懈", pinyin:"jiān chí bù xiè", chars:[{c:"坚",p:"jiān"},{c:"持",p:"chí"},{c:"不",p:"bù"},{c:"懈",p:"xiè"}],
    meaningCn:"坚持到底，毫不松懈。", meaningEn:"To persevere without relaxing one's efforts.",
    exampleCn:"只要坚持不懈，梦想终会实现。", examplePy:"Zhǐyào jiān chí bù xiè, mèngxiǎng zhōng huì shíxiàn.", exampleEn:"With persistence, dreams eventually come true.", tone:"G" },
  { idiom:"一鼓作气", pinyin:"yī gǔ zuò qì", chars:[{c:"一",p:"yī"},{c:"鼓",p:"gǔ"},{c:"作",p:"zuò"},{c:"气",p:"qì"}],
    meaningCn:"趁着一股劲，一下子把事情做完。形容趁劲头足时一口气完成。", meaningEn:"To make a decisive effort at one go; to finish in one burst.",
    exampleCn:"大家一鼓作气，提前完成了任务。", examplePy:"Dàjiā yī gǔ zuò qì, tíqián wánchéng le rènwu.", exampleEn:"Everyone finished the task in one determined push.", tone:"G" },
  { idiom:"再接再厉", pinyin:"zài jiē zài lì", chars:[{c:"再",p:"zài"},{c:"接",p:"jiē"},{c:"再",p:"zài"},{c:"厉",p:"lì"}],
    meaningCn:"一次又一次加倍努力。形容继续努力，毫不松懈。", meaningEn:"To keep up one's efforts; to press on with renewed vigor.",
    exampleCn:"希望你们再接再厉，取得更好成绩。", examplePy:"Xīwàng nǐmen zài jiē zài lì, qǔdé gèng hǎo chéngjì.", exampleEn:"Keep up the good work and aim even higher.", tone:"G" },
  { idiom:"循序渐进", pinyin:"xún xù jiàn jìn", chars:[{c:"循",p:"xún"},{c:"序",p:"xù"},{c:"渐",p:"jiàn"},{c:"进",p:"jìn"}],
    meaningCn:"按一定的步骤逐渐深入或提高。", meaningEn:"To proceed step by step and in due order.",
    exampleCn:"学习要循序渐进，不能急于求成。", examplePy:"Xuéxí yào xún xù jiàn jìn, bùnéng jíyúqiúchéng.", exampleEn:"Study proceeds step by step, never rushing.", tone:"G" },
  { idiom:"有的放矢", pinyin:"yǒu dì fàng shǐ", chars:[{c:"有",p:"yǒu"},{c:"的",p:"dì"},{c:"放",p:"fàng"},{c:"矢",p:"shǐ"}],
    meaningCn:"对准靶子射箭。比喻说话做事有针对性。", meaningEn:"To shoot at a target — to act with a clear purpose.",
    exampleCn:"解决问题要有的放矢，抓住关键。", examplePy:"Jiějué wèntí yào yǒu dì fàng shǐ, zhuāzhù guānjiàn.", exampleEn:"Address problems with a clear target.", tone:"G" },
  { idiom:"对症下药", pinyin:"duì zhèng xià yào", chars:[{c:"对",p:"duì"},{c:"症",p:"zhèng"},{c:"下",p:"xià"},{c:"药",p:"yào"}],
    meaningCn:"针对病症用药。比喻针对具体情况采取有效措施。", meaningEn:"To prescribe the right medicine for the illness; to suit the remedy to the case.",
    exampleCn:"老师对症下药，帮他改掉了坏习惯。", examplePy:"Lǎoshī duì zhèng xià yào, bāng tā gǎidiào le huài xíguàn.", exampleEn:"The teacher applied the right fix to his bad habit.", tone:"G" },
  { idiom:"因地制宜", pinyin:"yīn dì zhì yí", chars:[{c:"因",p:"yīn"},{c:"地",p:"dì"},{c:"制",p:"zhì"},{c:"宜",p:"yí"}],
    meaningCn:"根据不同地区的实际情况，制定适当的措施。", meaningEn:"To adapt measures to local conditions.",
    exampleCn:"发展经济要因地制宜，发挥本地优势。", examplePy:"Fāzhǎn jīngjì yào yīn dì zhì yí, fāhuī běndì yōushì.", exampleEn:"Develop the economy according to local conditions.", tone:"G" },
  { idiom:"随机应变", pinyin:"suí jī yìng biàn", chars:[{c:"随",p:"suí"},{c:"机",p:"jī"},{c:"应",p:"yìng"},{c:"变",p:"biàn"}],
    meaningCn:"随着情况的变化灵活应付。", meaningEn:"To adapt to changing circumstances; to act as the occasion requires.",
    exampleCn:"谈判时要随机应变，别死守方案。", examplePy:"Tánpàn shí yào suí jī yìng biàn, bié sǐshǒu fāng'àn.", exampleEn:"Stay flexible in negotiations, don't cling to one plan.", tone:"G" },
  { idiom:"审时度势", pinyin:"shěn shí duó shì", chars:[{c:"审",p:"shěn"},{c:"时",p:"shí"},{c:"度",p:"duó"},{c:"势",p:"shì"}],
    meaningCn:"观察分析时势，估计情况的变化。", meaningEn:"To size up the situation and gauge the trend.",
    exampleCn:"管理者要审时度势，及时调整策略。", examplePy:"Guǎnlǐzhě yào shěn shí duó shì, jíshí tiáozhěng cèlüè.", exampleEn:"A manager must read the situation and adjust strategy.", tone:"G" },
  { idiom:"运筹帷幄", pinyin:"yùn chóu wéi wò", chars:[{c:"运",p:"yùn"},{c:"筹",p:"chóu"},{c:"帷",p:"wéi"},{c:"幄",p:"wò"}],
    meaningCn:"在军帐中筹划计谋。比喻在后方谋划全局。", meaningEn:"To plan strategy behind the scenes; to mastermind.",
    exampleCn:"他运筹帷幄，指挥若定。", examplePy:"Tā yùn chóu wéi wò, zhǐhuī ruò dìng.", exampleEn:"He plans the strategy and directs with confidence.", tone:"G" },
  { idiom:"深思熟虑", pinyin:"shēn sī shú lǜ", chars:[{c:"深",p:"shēn"},{c:"思",p:"sī"},{c:"熟",p:"shú"},{c:"虑",p:"lǜ"}],
    meaningCn:"深入细致地思考，反复斟酌。", meaningEn:"To think deeply and consider carefully.",
    exampleCn:"经过深思熟虑，他作出了决定。", examplePy:"Jīngguò shēn sī shú lǜ, tā zuòchū le juédìng.", exampleEn:"After much deliberation, he made his decision.", tone:"G" },
  { idiom:"未雨绸缪", pinyin:"wèi yǔ chóu móu", chars:[{c:"未",p:"wèi"},{c:"雨",p:"yǔ"},{c:"绸",p:"chóu"},{c:"缪",p:"móu"}],
    meaningCn:"在没下雨前就修好门窗。比喻事先做好准备。", meaningEn:"To repair the roof before it rains — to prepare in advance.",
    exampleCn:"我们要未雨绸缪，提前制定应对方案。", examplePy:"Wǒmen yào wèi yǔ chóu móu, tíqián zhìdìng yìngduì fāng'àn.", exampleEn:"We should prepare in advance for rainy days.", tone:"G" },
  { idiom:"防患未然", pinyin:"fáng huàn wèi rán", chars:[{c:"防",p:"fáng"},{c:"患",p:"huàn"},{c:"未",p:"wèi"},{c:"然",p:"rán"}],
    meaningCn:"在祸患发生之前就加以防范。", meaningEn:"To take preventive measures before trouble arises.",
    exampleCn:"安全生产要防患未然，别等出事才后悔。", examplePy:"Ānquán shēngchǎn yào fáng huàn wèi rán, bié děng chūshì cái hòuhuǐ.", exampleEn:"Prevent accidents before they happen.", tone:"G" },
  { idiom:"居安思危", pinyin:"jū ān sī wēi", chars:[{c:"居",p:"jū"},{c:"安",p:"ān"},{c:"思",p:"sī"},{c:"危",p:"wēi"}],
    meaningCn:"处在安全的环境里，也要想到可能出现的危险。", meaningEn:"To think of danger in times of peace; to stay vigilant.",
    exampleCn:"越是顺利越要居安思危。", examplePy:"Yuè shì shùnlì yuè yào jū ān sī wēi.", exampleEn:"The smoother things go, the more vigilance is needed.", tone:"G" },
  { idiom:"有备无患", pinyin:"yǒu bèi wú huàn", chars:[{c:"有",p:"yǒu"},{c:"备",p:"bèi"},{c:"无",p:"wú"},{c:"患",p:"huàn"}],
    meaningCn:"事先有准备，就可以避免祸患。", meaningEn:"Preparedness averts calamity.",
    exampleCn:"提前做好备份，做到有备无患。", examplePy:"Tíqián zuòhǎo bèifèn, zuòdào yǒu bèi wú huàn.", exampleEn:"Back up in advance so you're prepared for anything.", tone:"G" },
  { idiom:"临危不惧", pinyin:"lín wēi bù jù", chars:[{c:"临",p:"lín"},{c:"危",p:"wēi"},{c:"不",p:"bù"},{c:"惧",p:"jù"}],
    meaningCn:"面临危险，毫不畏惧。", meaningEn:"To be fearless in the face of danger.",
    exampleCn:"危急关头，他临危不惧，挺身而出。", examplePy:"Wēijí guāntóu, tā lín wēi bù jù, tǐngshēn ér chū.", exampleEn:"At the critical moment he stood up fearlessly.", tone:"R" },
  { idiom:"处变不惊", pinyin:"chǔ biàn bù jīng", chars:[{c:"处",p:"chǔ"},{c:"变",p:"biàn"},{c:"不",p:"bù"},{c:"惊",p:"jīng"}],
    meaningCn:"面对变故，镇定自若，不惊慌。", meaningEn:"To remain calm in the face of change or crisis.",
    exampleCn:"他处变不惊，很快控制住了局面。", examplePy:"Tā chǔ biàn bù jīng, hěnkuài kòngzhì zhù le júmiàn.", exampleEn:"He stayed calm and quickly regained control.", tone:"G" },
  { idiom:"镇定自若", pinyin:"zhèn dìng zì ruò", chars:[{c:"镇",p:"zhèn"},{c:"定",p:"dìng"},{c:"自",p:"zì"},{c:"若",p:"ruò"}],
    meaningCn:"遇到紧急情况不慌不忙，像平常一样。", meaningEn:"To remain composed and unruffled.",
    exampleCn:"面对质疑，她镇定自若地回应。", examplePy:"Miànduì zhìyí, tā zhèn dìng zì ruò de huíyìng.", exampleEn:"She answered the doubts with composure.", tone:"G" },
  { idiom:"先发制人", pinyin:"xiān fā zhì rén", chars:[{c:"先",p:"xiān"},{c:"发",p:"fā"},{c:"制",p:"zhì"},{c:"人",p:"rén"}],
    meaningCn:"先动手以制服对方。比喻抢先一步，取得主动。", meaningEn:"To strike first and gain the initiative.",
    exampleCn:"谈判上要争取先发制人，掌握主动。", examplePy:"Tánpàn shàng yào zhēngqǔ xiān fā zhì rén, zhǎngwò zhǔdòng.", exampleEn:"Try to strike first and hold the initiative in talks.", tone:"R" },
  { idiom:"声东击西", pinyin:"shēng dōng jī xī", chars:[{c:"声",p:"shēng"},{c:"东",p:"dōng"},{c:"击",p:"jī"},{c:"西",p:"xī"}],
    meaningCn:"声张攻打东边，实际攻打西边。比喻迷惑对方，出其不意。", meaningEn:"To make a feint to the east and attack in the west.",
    exampleCn:"我军声东击西，打了敌人一个措手不及。", examplePy:"Wǒjūn shēng dōng jī xī, dǎ le dírén yí gè cuòshǒu bùjí.", exampleEn:"We feinted east and caught the enemy off guard in the west.", tone:"R" },
  { idiom:"调虎离山", pinyin:"diào hǔ lí shān", chars:[{c:"调",p:"diào"},{c:"虎",p:"hǔ"},{c:"离",p:"lí"},{c:"山",p:"shān"}],
    meaningCn:"设法使老虎离开山头。比喻用计使对方离开原来的有利位置。", meaningEn:"To lure the tiger away from the mountain — to entice the enemy from its stronghold.",
    exampleCn:"我们调虎离山，引开了守卫。", examplePy:"Wǒmen diào hǔ lí shān, yǐnkāi le shǒuwèi.", exampleEn:"We lured the guards away from their post.", tone:"R" },
  { idiom:"欲擒故纵", pinyin:"yù qín gù zòng", chars:[{c:"欲",p:"yù"},{c:"擒",p:"qín"},{c:"故",p:"gù"},{c:"纵",p:"zòng"}],
    meaningCn:"为了捉住对方，故意先放走他。比喻为了达到目的而先放松一步。", meaningEn:"To let someone go in order to catch them later.",
    exampleCn:"他欲擒故纵，先按兵不动。", examplePy:"Tā yù qín gù zòng, xiān ànbīng bùdòng.", exampleEn:"He held back to reel them in later.", tone:"R" },
  { idiom:"弄巧成拙", pinyin:"nòng qiǎo chéng zhuō", chars:[{c:"弄",p:"nòng"},{c:"巧",p:"qiǎo"},{c:"成",p:"chéng"},{c:"拙",p:"zhuō"}],
    meaningCn:"本想卖弄聪明，结果反而坏了事。", meaningEn:"To outsmart oneself; to make things worse by trying to be clever.",
    exampleCn:"本想帮倒忙，结果弄巧成拙。", examplePy:"Běnxiǎng bāng dǎománg, jiéguǒ nòng qiǎo chéng zhuō.", exampleEn:"He meant well but only made it worse.", tone:"R" },
  { idiom:"因小失大", pinyin:"yīn xiǎo shī dà", chars:[{c:"因",p:"yīn"},{c:"小",p:"xiǎo"},{c:"失",p:"shī"},{c:"大",p:"dà"}],
    meaningCn:"为了一点小利，反而造成大的损失。", meaningEn:"To lose the big for the small; to penny-pinch and lose more.",
    exampleCn:"别为省这点钱而因小失大。", examplePy:"Bié wèi shěng zhè diǎn qián ér yīn xiǎo shī dà.", exampleEn:"Don't lose more by trying to save a little.", tone:"R" },
  { idiom:"得不偿失", pinyin:"dé bù cháng shī", chars:[{c:"得",p:"dé"},{c:"不",p:"bù"},{c:"偿",p:"cháng"},{c:"失",p:"shī"}],
    meaningCn:"得到的抵不上失去的。", meaningEn:"The gains do not offset the losses.",
    exampleCn:"为这件事熬夜，得不偿失。", examplePy:"Wèi zhè jiàn shì áoyè, dé bù cháng shī.", exampleEn:"Staying up for this isn't worth the cost.", tone:"R" },
  { idiom:"本末倒置", pinyin:"běn mò dào zhì", chars:[{c:"本",p:"běn"},{c:"末",p:"mò"},{c:"倒",p:"dào"},{c:"置",p:"zhì"}],
    meaningCn:"把根本和枝叶搞颠倒了。比喻把主次、轻重弄反了。", meaningEn:"To put the cart before the horse; to invert priorities.",
    exampleCn:"抓工作不能本末倒置，要分清主次。", examplePy:"Zhuā gōngzuò bùnéng běn mò dào zhì, yào fēnqīng zhǔcì.", exampleEn:"Don't invert priorities; know what matters most.", tone:"R" },
  { idiom:"舍本逐末", pinyin:"shě běn zhú mò", chars:[{c:"舍",p:"shě"},{c:"本",p:"běn"},{c:"逐",p:"zhú"},{c:"末",p:"mò"}],
    meaningCn:"放弃根本，去追求细枝末节。比喻抓不住主要矛盾。", meaningEn:"To forsake the essential for the trivial.",
    exampleCn:"做研究请勿舍本逐末，忽略核心问题。", examplePy:"Zuò yánjiū qǐng wù shě běn zhú mò, hūlüè héxīn wèntí.", exampleEn:"Don't chase details while ignoring the core issue.", tone:"R" },
  { idiom:"轻重缓急", pinyin:"qīng zhòng huǎn jí", chars:[{c:"轻",p:"qīng"},{c:"重",p:"zhòng"},{c:"缓",p:"huǎn"},{c:"急",p:"jí"}],
    meaningCn:"指事情有主次、先后、紧要与缓和的差别。", meaningEn:"The order of importance and urgency of matters.",
    exampleCn:"安排工作要分清轻重缓急。", examplePy:"Ānpái gōngzuò yào fēnqīng qīng zhòng huǎn jí.", exampleEn:"Prioritize tasks by importance and urgency.", tone:"G" },
  { idiom:"有条不紊", pinyin:"yǒu tiáo bù wěn", chars:[{c:"有",p:"yǒu"},{c:"条",p:"tiáo"},{c:"不",p:"bù"},{c:"紊",p:"wěn"}],
    meaningCn:"有条理，有次序，一点不乱。", meaningEn:"Methodical and orderly; without a hitch.",
    exampleCn:"整个流程有条不紊，进展顺利。", examplePy:"Zhěnggè liúchéng yǒu tiáo bù wěn, jìnzhǎn shùnlì.", exampleEn:"The whole process ran smoothly and in order.", tone:"G" },
  { idiom:"井然有序", pinyin:"jǐng rán yǒu xù", chars:[{c:"井",p:"jǐng"},{c:"然",p:"rán"},{c:"有",p:"yǒu"},{c:"序",p:"xù"}],
    meaningCn:"整整齐齐，次序分明。", meaningEn:"Neat and orderly; well organized.",
    exampleCn:"现场井然有序，令人放心。", examplePy:"Xiànchǎng jǐng rán yǒu xù, lìngrén fàngxīn.", exampleEn:"The scene was perfectly organized.", tone:"G" },
  { idiom:"一目了然", pinyin:"yī mù liǎo rán", chars:[{c:"一",p:"yī"},{c:"目",p:"mù"},{c:"了",p:"liǎo"},{c:"然",p:"rán"}],
    meaningCn:"一眼就能看得清清楚楚。", meaningEn:"Clear at a glance; obvious at a single look.",
    exampleCn:"这张图表一目了然，很容易看懂。", examplePy:"Zhè zhāng túbiǎo yī mù liǎo rán, hěn róngyì kàndǒng.", exampleEn:"The chart is clear at a glance.", tone:"G" },
  { idiom:"恍然大悟", pinyin:"huǎng rán dà wù", chars:[{c:"恍",p:"huǎng"},{c:"然",p:"rán"},{c:"大",p:"dà"},{c:"悟",p:"wù"}],
    meaningCn:"一下子明白、醒悟过来。", meaningEn:"To suddenly realize the truth; to have an epiphany.",
    exampleCn:"他恍然大悟，原来误解了对方。", examplePy:"Tā huǎng rán dà wù, yuánlái wùjiě le duìfāng.", exampleEn:"It dawned on him that he had misunderstood.", tone:"R" },
  { idiom:"豁然开朗", pinyin:"huò rán kāi lǎng", chars:[{c:"豁",p:"huò"},{c:"然",p:"rán"},{c:"开",p:"kāi"},{c:"朗",p:"lǎng"}],
    meaningCn:"由狭窄昏暗突然变得开阔明亮。比喻一下子领悟，心情舒畅。", meaningEn:"Suddenly to see the light; to become clear and open.",
    exampleCn:"换个角度想，顿时豁然开朗。", examplePy:"Huàn gè jiǎodù xiǎng, dùnshí huò rán kāi lǎng.", exampleEn:"Looking from another angle, it suddenly became clear.", tone:"G" },
  { idiom:"茅塞顿开", pinyin:"máo sè dùn kāi", chars:[{c:"茅",p:"máo"},{c:"塞",p:"sè"},{c:"顿",p:"dùn"},{c:"开",p:"kāi"}],
    meaningCn:"好像心里被茅草塞住，忽然被打开了。比喻思想突然开窍。", meaningEn:"To have one's mind suddenly opened; to be enlightened.",
    exampleCn:"经他一点拨，我茅塞顿开。", examplePy:"Jīng tā yì diǎnbō, wǒ máo sè dùn kāi.", exampleEn:"After his hint, I suddenly saw the light.", tone:"G" },
  { idiom:"融会贯通", pinyin:"róng huì guàn tōng", chars:[{c:"融",p:"róng"},{c:"会",p:"huì"},{c:"贯",p:"guàn"},{c:"通",p:"tōng"}],
    meaningCn:"把各方面的知识融合贯穿起来，得到全面透彻的理解。", meaningEn:"To master knowledge by integrating it thoroughly.",
    exampleCn:"多加练习，便能融会贯通。", examplePy:"Duō jiā liànxí, biàn néng róng huì guàn tōng.", exampleEn:"With practice, you'll integrate it all.", tone:"G" },
  { idiom:"心领神会", pinyin:"xīn lǐng shén huì", chars:[{c:"心",p:"xīn"},{c:"领",p:"lǐng"},{c:"神",p:"shén"},{c:"会",p:"huì"}],
    meaningCn:"心里领会，不用对方明说。", meaningEn:"To understand without being told; to take the hint.",
    exampleCn:"他一个眼神，对方便心领神会。", examplePy:"Tā yí gè yǎnshén, duìfāng biàn xīn lǐng shén huì.", exampleEn:"With one look, the other understood perfectly.", tone:"G" },
  { idiom:"推陈出新", pinyin:"tuī chén chū xīn", chars:[{c:"推",p:"tuī"},{c:"陈",p:"chén"},{c:"出",p:"chū"},{c:"新",p:"xīn"}],
    meaningCn:"去掉旧的，创造新的。指在继承中创新。", meaningEn:"To discard the old and bring forth the new.",
    exampleCn:"传统艺术也需要推陈出新。", examplePy:"Chuántǒng yìshù yě xūyào tuī chén chū xīn.", exampleEn:"Traditional arts also need renewal.", tone:"G" },
  { idiom:"焕然一新", pinyin:"huàn rán yī xīn", chars:[{c:"焕",p:"huàn"},{c:"然",p:"rán"},{c:"一",p:"yī"},{c:"新",p:"xīn"}],
    meaningCn:"光彩夺目，呈现出崭新的面貌。", meaningEn:"To take on a brand-new look.",
    exampleCn:"装修之后，房间焕然一新。", examplePy:"Zhuāngxiū zhīhòu, fángjiān huàn rán yī xīn.", exampleEn:"After renovation, the room looks brand new.", tone:"G" },
  { idiom:"日新月异", pinyin:"rì xīn yuè yì", chars:[{c:"日",p:"rì"},{c:"新",p:"xīn"},{c:"月",p:"yuè"},{c:"异",p:"yì"}],
    meaningCn:"每天每月都有新的变化。形容发展进步很快。", meaningEn:"To change with each passing day; to advance rapidly.",
    exampleCn:"科技日新月异，我们要不断学习。", examplePy:"Kējì rì xīn yuè yì, wǒmen yào búduàn xuéxí.", exampleEn:"Technology advances daily; keep learning.", tone:"G" },
  { idiom:"突飞猛进", pinyin:"tū fēi měng jìn", chars:[{c:"突",p:"tū"},{c:"飞",p:"fēi"},{c:"猛",p:"měng"},{c:"进",p:"jìn"}],
    meaningCn:"形容进步和发展特别迅速。", meaningEn:"To make rapid progress; to advance by leaps and bounds.",
    exampleCn:"他的成绩突飞猛进，令人刮目相看。", examplePy:"Tā de chéngjì tū fēi měng jìn, lìngrén guāmù xiāngkàn.", exampleEn:"His progress has been rapid and impressive.", tone:"G" },
]);
